### ISSUE TITLE
UI: Landing page

### ISSUE THREAD

**Issue by Ojay-dev** [devcareer/Project-outside#3]

**Comment by skiboss** [comment]
https://github.com/devcareer/Project-outside/pull/11

**Comment by skiboss** [comment]
Still working on the responsiveness

**Comment by Ojay-dev** [comment]
Weldone @skiboss, checkout this little changes to be done

- The link in the navigation menu should have a hover and an active state as specified in the design
- The Logo should be in SVG and not PNG
- The "Find a show and publicize yours for free" text should not be centralised.


![Image](https://user-images.githubusercontent.com/52764057/207517768-14e2f57f-6ff2-48b3-abdc-8ae0e5a395fc.png)

**Comment by Ojay-dev** [comment]
Also for responsiveness, the image should comfortably sit on the top, while the rest of the contents should be below.

N.B: Responsiveness doesn’t start only at `767px` screen size


![Image](https://user-images.githubusercontent.com/52764057/207518529-87db1f35-6979-46e0-937c-0de7ee69e72a.png)
![Image](https://user-images.githubusercontent.com/52764057/207518530-c9da5a82-5258-4be4-9e6b-e6245148c2e2.png)

**Comment by skiboss** [comment]
https://github.com/devcareer/Project-outside/pull/11#partial-pull-merging
