### ISSUE TITLE
UI: Venues page

### ISSUE THREAD

**Issue by Ojay-dev** [devcareer/Project-outside#4]

**Comment by Eliteboss1** [comment]
https://github.com/devcareer/Project-outside/pull/12

**Comment by Ojay-dev** [comment]
Nice one @Eliteboss1, check out the changes required.

- Your page should be routed in `/venues` on react-router
- Your design should match the design on Figma
- Make the pagination a separate component
- Checkout your responsive view

**Comment by Eliteboss1** [comment]
ok sir I will start making the changes now.

**Comment by Eliteboss1** [comment]
https://github.com/devcareer/Project-outside/pull/12

**Comment by Eliteboss1** [comment]
https://github.com/devcareer/Project-outside/pull/12

**Comment by Eliteboss1** [comment]
https://github.com/devcareer/Project-outside/pull/12
