### ISSUE TITLE
UI: Shows page

### ISSUE THREAD

**Issue by Ojay-dev** [devcareer/Project-outside#9]

**Comment by CyberGeni** [comment]
i developed the page that displays the shows 
#6

**Comment by Ojay-dev** [comment]
Nice one @CyberGeni , though a little changes required

**Comment by Ojay-dev** [comment]
![Image](https://user-images.githubusercontent.com/52764057/207515774-47a2ad27-8b97-4fee-a4ae-807fef0ec903.png)

The show field should occupy a max-width on the desktop view, and the artist name and venue name should be a link.
